variable "env" {}
variable "component" {}
variable "tags" {
  default = {}
}
variable "subnets_ids" {}
variable "vpc_id" {}
variable "app_port" {}
variable "sg_subnets_cidr" {}
variable "kms_key_id" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "allow_ssh_cidr" {}
variable "lb_dns_name" {}
//variable "protocol" {}
variable "listener_arn" {}
variable "lb_rule_priority" {}
variable "kms_key_arn" {}